name       : libwpd
version    : 0.10.2
release    : 4
source     :
    - https://kent.dl.sourceforge.net/project/libwpd/libwpd/libwpd-0.10.2/libwpd-0.10.2.tar.xz : 323f68beaf4f35e5a4d7daffb4703d0566698280109210fa4eaa90dea27d6610
license    :
    - LGPL-2.1-or-later
    - MPL-2.0
component  : programming
summary    : Library for import of WordPerfect documents
description: |
    Libwpd is a library for import of WordPerfect documents.
builddeps  :
    - pkgconfig(librevenge-0.0)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-19208.patch
    %configure
build      : |
    %make
install    : |
    %make_install

