name       : libwpd
version    : 0.10.1
release    : 1
source     :
    - http://pilotfiber.dl.sourceforge.net/project/libwpd/libwpd/libwpd-0.10.1/libwpd-0.10.1.tar.xz : 09d3410bc770f9d9eedc8544b5c211771ea3322de3fee19b58ad7d40fb2984f6
license    :
    - LGPL-2.1
    - MPL-2.0
component  : programming
summary    : Library for import of WordPerfect documents
description: |
    Libwpd is a library for import of WordPerfect documents.
builddeps  :
    - pkgconfig(librevenge-0.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
